name: Build Library
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
    - release/**
permissions:
  contents: write
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
      versionCode: ${{ steps.run_number.outputs.versionCode }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.6
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display SemVer
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  build-android:
    needs:
    - version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        configuration:
        - buildCommand: :standardbutton:assembleRelease
          filesystemLocation: ./standardbutton/build/outputs/aar/standardbutton-release.aar
          artifactName: standardbutton-android.aar
          artifactKey: standardbutton-aar
          needsZip: false
          artifactMimeType: application/zip
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: ${{ matrix.configuration.buildCommand }}
    - name: Rename Artifact
      run: mv ${{ matrix.configuration.filesystemLocation }} ./${{ matrix.configuration.artifactName }}
    - name: Zip if needed
      if: ${{ matrix.configuration.needsZip }}
      run: zip -r ${{ matrix.configuration.artifactName }}.zip ./${{ matrix.configuration.artifactName }}
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.configuration.artifactKey }}
        path: ./${{ matrix.configuration.artifactName }}${{ matrix.configuration.needsZip && '.zip' || '' }}
  build-ios:
    needs:
    - version
    runs-on: macos-latest
    strategy:
      matrix:
        configuration:
        - buildCommand: :standardbutton:linkPodReleaseFrameworkIosArm64
          filesystemLocation: ./standardbutton/build/bin/iosArm64/podReleaseFramework/standardbutton.framework
          artifactName: standardbutton-iosArm64.framework
          artifactKey: standardbutton-iosArm64
          needsZip: true
          artifactMimeType: application/zip
        - buildCommand: :standardbutton:linkPodReleaseFrameworkIosSimulatorArm64
          filesystemLocation: ./standardbutton/build/bin/iosSimulatorArm64/podReleaseFramework/standardbutton.framework
          artifactName: standardbutton-iosSimulatorArm64.framework
          artifactKey: standardbutton-iosSimulatorArm64
          needsZip: true
          artifactMimeType: application/zip
        - buildCommand: :standardbutton:linkPodReleaseFrameworkIosX64
          filesystemLocation: ./standardbutton/build/bin/iosX64/podReleaseFramework/standardbutton.framework
          artifactName: standardbutton-iosX64.framework
          artifactKey: standardbutton-iosX64
          needsZip: true
          artifactMimeType: application/zip
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: ${{ matrix.configuration.buildCommand }}
    - name: Rename Artifact
      run: mv ${{ matrix.configuration.filesystemLocation }} ./${{ matrix.configuration.artifactName }}
    - name: Zip if needed
      if: ${{ matrix.configuration.needsZip }}
      run: zip -r ${{ matrix.configuration.artifactName }}.zip ./${{ matrix.configuration.artifactName }}
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.configuration.artifactKey }}
        path: ./${{ matrix.configuration.artifactName }}${{ matrix.configuration.needsZip && '.zip' || '' }}
  release:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  publish-release:
    needs:
    - version
    - release
    - build-android
    - build-ios
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
        - key: standardbutton-iosArm64
          name: standardbutton-iosArm64.framework.zip
          mimeType: application/zip
        - key: standardbutton-iosSimulatorArm64
          name: standardbutton-iosSimulatorArm64.framework.zip
          mimeType: application/zip
        - key: standardbutton-iosX64
          name: standardbutton-iosX64.framework.zip
          mimeType: application/zip
        - key: standardbutton-aar
          name: standardbutton-android.aar
          mimeType: application/zip
    steps:
    - uses: actions/download-artifact@master
      with:
        name: ${{ matrix.artifact.key }}
        path: ./
    - name: Add version to file name
      run: |-
        file="${{ matrix.artifact.name }}"
        echo "NEW_NAME=${file%%.*}-v${{ needs.version.outputs.version }}.${file#*.}" >> $GITHUB_ENV
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./${{ matrix.artifact.name }}
        asset_name: ${{ env.NEW_NAME }}
        asset_content_type: ${{ matrix.artifact.mimeType }}
  publish-sonatype:
    permissions:
      contents: read
    needs:
    - version
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    strategy:
      matrix:
        module:
        - standardbutton
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SECRET_KMP }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: |-
          -Pversion=${{ needs.version.outputs.version }}
          -Ppom.url="https://github.com/${{ github.repository }}"
          -Ppom.scm.connection="scm:git:git://github.com/${{ github.repository }}"
          -Ppom.scm.developerConnection="scm:git:ssh://github.com/${{ github.repository }}"
          -Ppom.scm.url="https://github.com/${{ github.repository }}"
          ${{ matrix.module }}:publishAndReleaseToMavenCentral --no-configuration-cache
