name: Build
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
    - release/**
permissions:
  contents: write
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
      versionCode: ${{ steps.run_number.outputs.versionCode }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.6
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v0.9.6
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - name: Display SemVer
      run: 'echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"'
  build:
    needs:
    - version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - standardbutton
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: ${{ matrix.module }}:build
    - name: Rename AAR
      run: mv ./${{ matrix.module }}/build/outputs/aar/${{ matrix.module }}-${{ needs.version.outputs.version }}.aar ./${{ matrix.module }}.aar
    - uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.module }}-aar
        path: ./${{ matrix.module }}.aar
  release:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  publish-release:
    needs:
    - version
    - release
    - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - standardbutton
    steps:
    - uses: actions/download-artifact@master
      with:
        name: ${{ matrix.module }}-aar
        path: ./
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./${{ matrix.module }}.aar
        asset_name: ${{ matrix.module }}-v${{ needs.version.outputs.version }}.aar
        asset_content_type: application/zip
  publish-sonatype:
    permissions:
      contents: read
    needs:
    - version
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
        - standardbutton
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: temurin
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: |-
          -Pversion=${{ needs.version.outputs.version }} 
          -Ppom.url="https://github.com/${{ github.repository }}" 
          -Ppom.scm.connection="scm:git:git://github.com/${{ github.repository }}" 
          -Ppom.scm.developerConnection="scm:git:ssh://github.com/${{ github.repository }}" 
          -Ppom.scm.url="https://github.com/${{ github.repository }}" 
          ${{ matrix.module }}:publishToCentralPortal --no-daemon
