name: Build Library
'on':
  pull_request:
    branches:
    - main
    - develop
  push:
    branches:
    - main
    - develop
    - release/**
permissions:
  contents: write
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
      versionCode: ${{ steps.run-number.outputs.versionCode }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: 5.x
    - id: gitversion
      name: Use GitVersion
      uses: gittools/actions/gitversion/execute@v3.0.0
      with:
        useConfigFile: true
        configFilePath: ./gitversion.yml
    - id: run-number
      run: |-
        current_run_number=${{ github.run_number }}
        new_number=$((current_run_number+0))
        echo "versionCode=${new_number}" >> $GITHUB_OUTPUT
    - name: Generate Job Summary
      run: |-
        echo "# Version Info
        Semantic Version: ${{ steps.gitversion.outputs.semVer }}
        Version Number: ${{ steps.run-number.outputs.versionCode }}" >> $GITHUB_STEP_SUMMARY
  build:
    needs:
    - version
    runs-on: ${{ matrix.configuration.os }}
    strategy:
      matrix:
        configuration:
        - command: :standardbutton:assembleRelease
          os: ubuntu-latest
          output0:
            key: standardbutton-android-aar
            name: standardbutton-android.aar
            location: ./standardbutton/build/outputs/aar/standardbutton-release.aar
            needsZip: false
        - command: :standardbutton:jvmJar
          os: ubuntu-latest
          output0:
            key: standardbutton-jvm-jar
            name: standardbutton-jvm.jar
            location: ./standardbutton/build/libs/standardbutton-jvm-${{ needs.version.outputs.version }}.jar
            needsZip: false
        - command: :standardbutton:wasmJsJar
          os: ubuntu-latest
          output0:
            key: standardbutton-wasm-js-klib
            name: standardbutton-wasm-js.klib
            location: ./standardbutton/build/libs/standardbutton-wasm-js-${{ needs.version.outputs.version }}.klib
            needsZip: false
        - command: :standardbutton:jsJar
          os: ubuntu-latest
          output0:
            key: standardbutton-js-klib
            name: standardbutton-js.klib
            location: ./standardbutton/build/libs/standardbutton-js-${{ needs.version.outputs.version }}.klib
            needsZip: false
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_version: ${{ needs.version.outputs.version }}
      run: ./gradlew ${{ matrix.configuration.command }}
    - name: Rename Artifact (Output 0)
      if: contains(toJSON(matrix.configuration), 'output0')
      run: mv ${{ matrix.configuration.output0.location }} ./${{ matrix.configuration.output0.name }}
    - name: Zip if Needed (Output 0)
      if: contains(toJSON(matrix.configuration), 'output0') && matrix.configuration.output0.needsZip
      run: zip -r ${{ matrix.configuration.output0.name }}.zip ./${{ matrix.configuration.output0.name }}
    - name: Upload Artifact (Output 0)
      if: contains(toJSON(matrix.configuration), 'output0')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration.output0.key }}
        path: ./${{ matrix.configuration.output0.name }}${{ matrix.configuration.output0.needsZip && '.zip' || '' }}
    - name: Rename Artifact (Output 1)
      if: contains(toJSON(matrix.configuration), 'output1')
      run: mv ${{ matrix.configuration.output1.location }} ./${{ matrix.configuration.output1.name }}
    - name: Zip if Needed (Output 1)
      if: contains(toJSON(matrix.configuration), 'output1') && matrix.configuration.output1.needsZip
      run: zip -r ${{ matrix.configuration.output1.name }}.zip ./${{ matrix.configuration.output1.name }}
    - name: Upload Artifact (Output 1)
      if: contains(toJSON(matrix.configuration), 'output1')
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.configuration.output1.key }}
        path: ./${{ matrix.configuration.output1.name }}${{ matrix.configuration.output1.needsZip && '.zip' || '' }}
  release:
    permissions:
      contents: write
    needs:
    - version
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Create tag for release
      uses: rickstaa/action-create-tag@v1
      with:
        tag: v${{ needs.version.outputs.version }}
    - id: create_release
      name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: v${{ needs.version.outputs.version }}
        name: Release ${{ needs.version.outputs.version }}
        draft: false
        prerelease: ${{ github.ref != 'refs/heads/main' }}
  publish-release:
    needs:
    - version
    - release
    - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact:
        - key: standardbutton-android-aar
          name: standardbutton-android.aar
          mimeType: application/zip
        - key: standardbutton-jvm-jar
          name: standardbutton-jvm.jar
          mimeType: application/zip
        - key: standardbutton-wasm-js-klib
          name: standardbutton-wasm-js.klib
          mimeType: application/zip
        - key: standardbutton-js-klib
          name: standardbutton-js.klib
          mimeType: application/zip
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.artifact.key }}
        path: ./
    - name: Add version to file name
      run: |-
        file="${{ matrix.artifact.name }}"
        echo "NEW_NAME=${file%%.*}-v${{ needs.version.outputs.version }}.${file#*.}" >> $GITHUB_ENV
    - name: Upload Artifact to Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: shogo82148/actions-upload-release-asset@v1
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ./${{ matrix.artifact.name }}
        asset_name: ${{ env.NEW_NAME }}
        asset_content_type: ${{ matrix.artifact.mimeType }}
  publish-sonatype:
    permissions:
      contents: read
    needs:
    - version
    if: github.ref == 'refs/heads/main'
    runs-on: macos-latest
    strategy:
      matrix:
        module:
        - standardbutton
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
    - name: Setup gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SECRET_KMP }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_PASSPHRASE }}
      run: |-
        ./gradlew -Pversion=${{ needs.version.outputs.version }} \
        -Ppom.url="https://github.com/${{ github.repository }}" \
        -Ppom.scm.connection="scm:git:git://github.com/${{ github.repository }}" \
        -Ppom.scm.developerConnection="scm:git:ssh://github.com/${{ github.repository }}" \
        -Ppom.scm.url="https://github.com/${{ github.repository }}" \
        ${{ matrix.module }}:publishToMavenCentral --no-configuration-cache
